name: 💫 YGitBook Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: 🏗️ Python ${{ matrix.python-version }} kurulması
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: 📦 Bağımlılıkların kurulması
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 🚧 Açıklamaların oluşturulması
      run: |
        python name-generator.py
    - name: 💫 GitBook uyumluluğunun sağlanması
      run: |
        ygitbookintegration .
    - name: 🔀 Değişiklerin commit edilmesi
      run: |
        git config --local user.email "yedhrab@gmail.com"
        git config --local user.name "yedhrab"
        echo `git add -A && git commit -m "💫 GitBook entegrasyonu yapıldı"`
    - name: 🎉 GitHub push işlemi
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.YGITBOOK_INTEGRATION }}


